# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

before_install:
  - gem install cocoapods --version 1.5.0

matrix:
  include:
  - name: "Xcode 9.4 iOS 11.3"
    osx_image: xcode9.4
    env: DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=11.3' UI=true
  - name: "Xcode 9.4 iOS 10.3.1"
    osx_image: xcode9.4
    env: DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=10.3.1' UI=true
  - name: "Xcode 10 iOS 11.3"
    osx_image: xcode10
    env: DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=11.3' UI=true
  - name: "Xcode 10 iOS 10.3.1"
    osx_image: xcode10
    env: DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=10.3.1' UI=true

script:
- set -o pipefail
- travis/validate_carthage.sh
- xcodebuild -destination "$DESTINATION" -workspace Example/XCTest-Gherkin.xcworkspace -scheme XCTest-Gherkin-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty -f `xcpretty-gherkin-formatter/bin/xcpretty-gherkin-formatter`
- if [ $UI ]; then xcodebuild -destination "$DESTINATION" -workspace Example/XCTest-Gherkin.xcworkspace -scheme XCTest-Gherkin-Example-UI -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty -f `xcpretty-gherkin-formatter/bin/xcpretty-gherkin-formatter`; fi
- pod lib lint --allow-warnings
