# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift

before_install:
  - gem install xcpretty

matrix:
  include:
  - name: "Xcode 10.2 iOS 12.2"
    osx_image: xcode10.2
    env: DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=12.2' UI=true
  - name: "Xcode 10.2 iOS 11.3"
    osx_image: xcode10.2
    env: DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=11.3' UI=true
  - name: "Xcode 10.2 iOS 10.3.1"
    osx_image: xcode10.2
    env: DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=10.3.1' UI=true

script:
- set -o pipefail
- travis/validate_carthage.sh
- xcodebuild -destination "$DESTINATION" -workspace Example/XCTest-Gherkin.xcworkspace -scheme XCTest-Gherkin-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty
- if [ $UI ]; then xcodebuild -destination "$DESTINATION" -workspace Example/XCTest-Gherkin.xcworkspace -scheme XCTest-Gherkin-Example-UI -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty; fi
- bundle exec pod lib lint --allow-warnings
